// <auto-generated />
namespace DAL.Context.Persistance
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitWithSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitWithSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "202405150915079_InitWithSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
